version: "3.3"

services:
  wp-api-db:
    image: mysql:5.7
    volumes:
      - ./temp/wp-database:/var/lib/mysql
    command: --log_error_verbosity=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wp-api:
    build: https://github.com/minas-dev-test/farma-news.git
    depends_on:
      - wp-api-db
    ports:
      - "3001:80"
    environment:
      WORDPRESS_DB_HOST: wp-api-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_URL: "http://localhost:3001"
      WORDPRESS_TITLE: "Farma News"

  api-pda-db:
    image: mongo

  api-pda:
    build: https://github.com/minas-dev-test/api-pda.git
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://api-pda-db:27017/ufjf
    depends_on:
      - api-pda-db

  medicamentos-api-db:
    image: mysql:5.7
    volumes:
      - ./temp/med-database:/var/lib/mysql
    command: --log_error_verbosity=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicamentodb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  
  medicamentos-api:
    build: https://github.com/minas-dev-test/farma_medicamento.git
    depends_on:
      - medicamentos-api-db
    command: wait-for-it medicamentos-api-db:3306 --timeout=0 -- java -jar app.jar
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:mysql://medicamentos-api-db:3306/medicamentodb"
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

  auth-db:
    image: mongo
    ports:
      - "27018:27017"

  middleware:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3010:3010"
    depends_on:
      - auth-db
    environment:
      # MS_NEWS: "http://wp-api"
      # MS_LOCATION: "http://api-pda:8080"
      # MS_MEDICINE: "http://medicamentos-api:8080"
      PORT: 3010
      MS_NEWS: "http://farmaciasolidaria.ddns.net:3000"
      MS_LOCATION: "https://farmaciasolidaria-location.herokuapp.com"
      MS_MEDICINE: "https://farmaciasolidaria-medicine.herokuapp.com"
      MONGODB_URI: mongodb://auth-db:27017/farmacia
      GATEWAY_ADMIN_USER: admin
      GATEWAY_ADMIN_PASSWORD: admin
      GATEWAY_ADMIN_MAIL: admin@example.com
